---
language: ruby

script: bundle exec rake

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libarchive-dev

rvm:
  - 2.1
  - jruby

notifications:
  email:
    recipients:
      - development+travis-opener@olery.com

    on_success: change
    on_failure: change

cache: bundler

branches:
  only:
    - master
